version: '3.7'
services:
  register:
    container_name: register
    build: ./receitex_register
    ports:
      - 8761:8761
    environment:
      server.port: 8761
      eureka.instance.hostname: receitex_register
      eureka.client.serviceUrl.defaultZone: http://register:8761/eureka
    restart: unless-stopped
    networks:
      - receitex_microsservices

  receitex-gateway:
    container_name: receitex_gateway
    build: ./receitex_gateway
    ports:
      - 8080:8080
    depends_on:
      - register
    environment:
      eureka.client.serviceUrl.defaultZone: http://register:8761/eureka
      eureka.instance.preferIpAddress: false
    restart: unless-stopped
    networks:
      - receitex_microsservices

networks:
  receitex_microsservices:
    name: receitex_microsservices_net
    driver: bridge

