services:
  receitex_notification_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: receitex_notification_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5434
    networks:
      - receitex_notification
  receitex_notification_app:
    container_name: receitex-auth-app
    build: .
    ports:
      - 8083:8083
    environment:
      eureka.client.serviceUrl.defaultzone: http://receitex_register:8761/eureka
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.url: jdbc:postgresql://receitex_notification_db:5432/receitex_notification_db
      server.port: 8083
    restart: unless-stopped
    depends_on:
      - receitex_notification_db
    networks:
      - receitex_microsservices
      - receitex_notification

networks:
    receitex_microsservices:
      name: receitex_microsservices_net
      external: true
    receitex_notification:
      name: receitex_notification_net

