services:
  receitex_auth_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: receitex_auth_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5433
    networks:
      - receitex_auth
  receitex_auth_app:
    container_name: receitex-auth-app
    build: .
    ports:
      - 8082:8082
    environment:
      eureka.instance.preferIpAddress: false
      eureka.client.serviceUrl.defaultZone: http://register:8761/eureka
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.url: jdbc:postgresql://receitex_auth_db:5432/receitex_auth_db

      server.port: 8082
    restart: unless-stopped
    depends_on:
      - receitex_auth_db
    networks:
      - receitex_microsservices
      - receitex_auth

networks:
  receitex_microsservices:
    name: receitex_microsservices_net
    external: true
  receitex_auth:
    name: receitex_auth_net
